import 'package:powersync/powersync.dart';

/// PowerSync local schema definition.
///
/// Must mirror the Supabase Postgres schema declared in
/// supabase/migrations/20260607000000_init_schema.sql. PowerSync uses this
/// to materialise the synced rows into a local SQLite database it manages
/// itself (separate from the legacy `gestanea.db` opened by DatabaseHelper).
///
/// Columns: we deliberately model everything as TEXT here. PowerSync stores
/// values as TEXT regardless and Dart parses on read — keeps the schema
/// dead simple and matches the JSON/REST round-trip on the wire.
const _userTables = <Table>[
  Table('users', [
    Column.text('email'),
    Column.text('name'),
    Column.text('phone'),
    Column.text('country'),
    Column.text('language'),
    Column.text('theme'),
    Column.integer('notifications_enabled'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
  Table('pregnancies', [
    Column.text('user_id'),
    Column.text('lmp_date'),
    Column.text('due_date'),
    Column.integer('current_week'),
    Column.text('current_trimester'),
    Column.integer('is_active'),
    Column.text('medical_conditions'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ], indexes: [
    Index('by_user', [IndexedColumn('user_id')]),
  ]),
  Table('kick_counts', [
    Column.text('user_id'),
    Column.integer('kick_count'),
    Column.integer('duration_minutes'),
    Column.text('recorded_at'),
    Column.text('notes'),
    Column.text('created_at'),
  ]),
  Table('babies', [
    Column.text('user_id'),
    Column.text('name'),
    Column.text('gender'),
    Column.text('date_of_birth'),
    Column.real('birth_weight'),
    Column.real('birth_height'),
    Column.text('theme_color'),
    Column.integer('is_active'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
  Table('baby_growth', [
    Column.text('baby_id'),
    Column.text('recorded_date'),
    Column.real('weight'),
    Column.integer('weight_percentile'),
    Column.integer('height_percentile'),
    Column.text('growth_status'),
    Column.text('notes'),
    Column.text('created_at'),
  ]),
  Table('milestones', [
    Column.text('baby_id'),
    Column.text('milestone_name'),
    Column.integer('expected_age_months'),
    Column.text('achieved_date'),
    Column.text('notes'),
    Column.text('created_at'),
  ]),
  Table('feeding_logs', [
    Column.text('baby_id'),
    Column.text('feeding_type'),
    Column.integer('duration_minutes'),
    Column.real('amount_ml'),
    Column.text('breast_side'),
    Column.text('logged_at'),
    Column.text('notes'),
    Column.text('created_at'),
  ]),
  Table('vitals', [
    Column.text('user_id'),
    Column.text('vital_type'),
    Column.real('value'),
    Column.text('unit'),
    Column.text('recorded_at'),
    Column.text('notes'),
    Column.text('created_at'),
  ]),
  Table('measurements', [
    Column.text('user_id'),
    Column.real('weight'),
    Column.integer('heart_rate'),
    Column.integer('systolic'),
    Column.integer('diastolic'),
    Column.text('recorded_at'),
    Column.text('notes'),
    Column.text('created_at'),
  ]),
  Table('symptoms', [
    Column.text('user_id'),
    Column.text('symptom_name'),
    Column.text('severity'),
    Column.text('notes'),
    Column.text('recorded_at'),
    Column.text('created_at'),
  ]),
  Table('moods', [
    Column.text('user_id'),
    Column.text('mood'),
    Column.integer('intensity'),
    Column.text('notes'),
    Column.text('recorded_at'),
    Column.text('created_at'),
  ]),
  Table('lab_results', [
    Column.text('user_id'),
    Column.text('test_name'),
    Column.real('value'),
    Column.text('unit'),
    Column.real('normal_range_min'),
    Column.real('normal_range_max'),
    Column.text('interpretation'),
    Column.text('lab_date'),
    Column.text('report_image_url'),
    Column.integer('extracted_by_ocr'),
    Column.text('created_at'),
  ]),
  Table('risk_alerts', [
    Column.text('user_id'),
    Column.text('alert_type'),
    Column.text('severity'),
    Column.text('message'),
    Column.text('recommendation'),
    Column.integer('is_resolved'),
    Column.text('detected_at'),
    Column.text('resolved_at'),
    Column.text('created_at'),
  ]),
  Table('appointments', [
    Column.text('user_id'),
    Column.text('baby_id'),
    Column.text('title'),
    Column.text('doctor_name'),
    Column.text('appointment_type'),
    Column.text('appointment_date'),
    Column.text('location'),
    Column.text('notes'),
    Column.text('reminder_time'),
    Column.integer('is_completed'),
    Column.text('created_at'),
  ]),
  Table('medicines', [
    Column.text('user_id'),
    Column.text('baby_id'),
    Column.text('medicine_name'),
    Column.text('dosage'),
    Column.text('type'),
    Column.text('frequency_type'),
    Column.integer('frequency_value'),
    Column.text('scheduled_times'),
    Column.text('start_date'),
    Column.text('end_date'),
    Column.text('medicine_image_url'),
    Column.integer('is_active'),
    Column.text('created_at'),
  ]),
  Table('medicine_logged', [
    Column.text('medicine_id'),
    Column.text('user_id'),
    Column.text('logged_date'),
    Column.text('status'),
    Column.text('notes'),
    Column.text('logged_at'),
  ]),
  Table('reminders', [
    Column.text('user_id'),
    Column.text('reminder_type'),
    Column.text('reference_id'),
    Column.text('title'),
    Column.text('description'),
    Column.text('reminder_time'),
    Column.text('repeat_pattern'),
    Column.integer('is_completed'),
    Column.text('completed_at'),
    Column.text('created_at'),
  ]),
  Table('user_saved_tips', [
    Column.text('user_id'),
    Column.text('tip_id'),
    Column.text('saved_at'),
  ]),
  Table('product_reviews', [
    Column.text('product_id'),
    Column.text('user_id'),
    Column.text('reviewer_name'),
    Column.integer('rating'),
    Column.text('review_text'),
    Column.text('created_at'),
  ]),
  Table('cart_items', [
    Column.text('user_id'),
    Column.text('product_id'),
    Column.text('product_name'),
    Column.real('product_price'),
    Column.text('variant_color'),
    Column.text('variant_size'),
    Column.integer('quantity'),
    Column.text('added_at'),
  ]),
  Table('orders', [
    Column.text('user_id'),
    Column.text('full_name'),
    Column.text('phone_number'),
    Column.text('delivery_address'),
    Column.text('city'),
    Column.text('special_instructions'),
    Column.text('payment_method'),
    Column.real('subtotal'),
    Column.real('delivery_fee'),
    Column.real('total_amount'),
    Column.text('status'),
    Column.text('order_date'),
    Column.text('created_at'),
  ]),
  Table('order_items', [
    Column.text('order_id'),
    Column.text('product_id'),
    Column.text('product_name'),
    Column.text('variant_color'),
    Column.text('variant_size'),
    Column.integer('quantity'),
    Column.real('unit_price'),
    Column.real('subtotal'),
  ]),
];

const _catalogTables = <Table>[
  Table('tips', [
    Column.text('title'),
    Column.text('content'),
    Column.text('category'),
    Column.text('target_audience'),
    Column.text('image_url'),
    Column.text('source'),
    Column.integer('is_active'),
    Column.text('created_at'),
  ]),
  Table('doctors', [
    Column.text('name'),
    Column.text('specialty'),
    Column.real('distance'),
    Column.text('gender'),
    Column.text('phone'),
    Column.text('email'),
    Column.real('latitude'),
    Column.real('longitude'),
    Column.real('rating'),
    Column.integer('reviews_count'),
    Column.text('address'),
    Column.integer('isfavorite'),
    Column.text('wilaya'),
  ]),
  Table('product_categories', [
    Column.text('name'),
    Column.text('image_url'),
    Column.integer('display_order'),
    Column.text('created_at'),
  ]),
  Table('products', [
    Column.text('product_name'),
    Column.text('description'),
    Column.text('category_id'),
    Column.text('target_audience'),
    Column.real('price'),
    Column.real('original_price'),
    Column.integer('discount_percentage'),
    Column.text('currency'),
    Column.real('rating'),
    Column.integer('reviews_count'),
    Column.text('image_urls'),
    Column.text('vendor_name'),
    Column.integer('is_available'),
    Column.text('created_at'),
  ]),
  Table('product_variants', [
    Column.text('product_id'),
    Column.text('type'),
    Column.text('value'),
    Column.text('color_hex'),
    Column.integer('stock'),
    Column.text('created_at'),
  ]),
  Table('product_specs', [
    Column.text('product_id'),
    Column.text('name'),
    Column.text('value'),
    Column.text('created_at'),
  ]),
];

final powerSyncSchema = Schema([..._userTables, ..._catalogTables]);
