// Mocks generated by Mockito 5.4.6 from annotations
// in gestanea/test/unit/blocs/measurements_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:gestanea/core/database/models/measurement_model.dart' as _i4;
import 'package:gestanea/core/services/measurements_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [MeasurementsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMeasurementsService extends _i1.Mock
    implements _i2.MeasurementsService {
  MockMeasurementsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.MeasurementModel>> getMeasurements() =>
      (super.noSuchMethod(
            Invocation.method(#getMeasurements, []),
            returnValue: _i3.Future<List<_i4.MeasurementModel>>.value(
              <_i4.MeasurementModel>[],
            ),
          )
          as _i3.Future<List<_i4.MeasurementModel>>);

  @override
  _i3.Future<void> addMeasurement(_i4.MeasurementModel? measurement) =>
      (super.noSuchMethod(
            Invocation.method(#addMeasurement, [measurement]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateMeasurement(_i4.MeasurementModel? measurement) =>
      (super.noSuchMethod(
            Invocation.method(#updateMeasurement, [measurement]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteMeasurement(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMeasurement, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.MeasurementModel?> getLatestMeasurement() =>
      (super.noSuchMethod(
            Invocation.method(#getLatestMeasurement, []),
            returnValue: _i3.Future<_i4.MeasurementModel?>.value(),
          )
          as _i3.Future<_i4.MeasurementModel?>);

  @override
  _i3.Future<List<_i4.MeasurementModel>> getMeasurementsByDateRange(
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMeasurementsByDateRange, [
              startDate,
              endDate,
            ]),
            returnValue: _i3.Future<List<_i4.MeasurementModel>>.value(
              <_i4.MeasurementModel>[],
            ),
          )
          as _i3.Future<List<_i4.MeasurementModel>>);

  @override
  _i3.Future<void> syncNow() =>
      (super.noSuchMethod(
            Invocation.method(#syncNow, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<int> getUnsyncedCount() =>
      (super.noSuchMethod(
            Invocation.method(#getUnsyncedCount, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);
}
