// Mocks generated by Mockito 5.4.6 from annotations
// in gestanea/test/unit/blocs/plan_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:gestanea/core/database/models/appointment_model.dart' as _i7;
import 'package:gestanea/core/database/models/medicine_logged_model.dart'
    as _i6;
import 'package:gestanea/core/database/models/medicine_model.dart' as _i5;
import 'package:gestanea/core/services/alarm_scheduler.dart' as _i8;
import 'package:gestanea/features/plan/data/repositories/appointment_repository.dart'
    as _i3;
import 'package:gestanea/features/plan/data/repositories/medicine_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeReturnResult_0 extends _i1.SmartFake implements _i2.ReturnResult {
  _FakeReturnResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeReturnResult_1 extends _i1.SmartFake implements _i3.ReturnResult {
  _FakeReturnResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MedicineRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMedicineRepository extends _i1.Mock
    implements _i2.MedicineRepository {
  MockMedicineRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.MedicineModel>> getMedicines(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getMedicines, [userId]),
            returnValue: _i4.Future<List<_i5.MedicineModel>>.value(
              <_i5.MedicineModel>[],
            ),
          )
          as _i4.Future<List<_i5.MedicineModel>>);

  @override
  _i4.Future<List<_i5.MedicineModel>> getMedicinesByDate(
    String? userId,
    DateTime? date,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMedicinesByDate, [userId, date]),
            returnValue: _i4.Future<List<_i5.MedicineModel>>.value(
              <_i5.MedicineModel>[],
            ),
          )
          as _i4.Future<List<_i5.MedicineModel>>);

  @override
  _i4.Future<List<_i6.MedicineLoggedModel>> getMedicineLogs(
    String? userId,
    DateTime? date,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMedicineLogs, [userId, date]),
            returnValue: _i4.Future<List<_i6.MedicineLoggedModel>>.value(
              <_i6.MedicineLoggedModel>[],
            ),
          )
          as _i4.Future<List<_i6.MedicineLoggedModel>>);

  @override
  _i4.Future<_i2.ReturnResult> insertMedicine(_i5.MedicineModel? medicine) =>
      (super.noSuchMethod(
            Invocation.method(#insertMedicine, [medicine]),
            returnValue: _i4.Future<_i2.ReturnResult>.value(
              _FakeReturnResult_0(
                this,
                Invocation.method(#insertMedicine, [medicine]),
              ),
            ),
          )
          as _i4.Future<_i2.ReturnResult>);

  @override
  _i4.Future<_i2.ReturnResult> updateMedicine(_i5.MedicineModel? medicine) =>
      (super.noSuchMethod(
            Invocation.method(#updateMedicine, [medicine]),
            returnValue: _i4.Future<_i2.ReturnResult>.value(
              _FakeReturnResult_0(
                this,
                Invocation.method(#updateMedicine, [medicine]),
              ),
            ),
          )
          as _i4.Future<_i2.ReturnResult>);

  @override
  _i4.Future<_i2.ReturnResult> deleteMedicine(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMedicine, [id]),
            returnValue: _i4.Future<_i2.ReturnResult>.value(
              _FakeReturnResult_0(
                this,
                Invocation.method(#deleteMedicine, [id]),
              ),
            ),
          )
          as _i4.Future<_i2.ReturnResult>);

  @override
  _i4.Future<_i2.ReturnResult> logMedicine(_i6.MedicineLoggedModel? log) =>
      (super.noSuchMethod(
            Invocation.method(#logMedicine, [log]),
            returnValue: _i4.Future<_i2.ReturnResult>.value(
              _FakeReturnResult_0(this, Invocation.method(#logMedicine, [log])),
            ),
          )
          as _i4.Future<_i2.ReturnResult>);
}

/// A class which mocks [AppointmentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppointmentRepository extends _i1.Mock
    implements _i3.AppointmentRepository {
  MockAppointmentRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i7.AppointmentModel>> getAppointments(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getAppointments, [userId]),
            returnValue: _i4.Future<List<_i7.AppointmentModel>>.value(
              <_i7.AppointmentModel>[],
            ),
          )
          as _i4.Future<List<_i7.AppointmentModel>>);

  @override
  _i4.Future<List<_i7.AppointmentModel>> getAppointmentsByDate(
    String? userId,
    DateTime? date,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAppointmentsByDate, [userId, date]),
            returnValue: _i4.Future<List<_i7.AppointmentModel>>.value(
              <_i7.AppointmentModel>[],
            ),
          )
          as _i4.Future<List<_i7.AppointmentModel>>);

  @override
  _i4.Future<List<_i7.AppointmentModel>> getUpcomingAppointments(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUpcomingAppointments, [userId]),
            returnValue: _i4.Future<List<_i7.AppointmentModel>>.value(
              <_i7.AppointmentModel>[],
            ),
          )
          as _i4.Future<List<_i7.AppointmentModel>>);

  @override
  _i4.Future<_i3.ReturnResult> insertAppointment(
    _i7.AppointmentModel? appointment,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#insertAppointment, [appointment]),
            returnValue: _i4.Future<_i3.ReturnResult>.value(
              _FakeReturnResult_1(
                this,
                Invocation.method(#insertAppointment, [appointment]),
              ),
            ),
          )
          as _i4.Future<_i3.ReturnResult>);

  @override
  _i4.Future<_i3.ReturnResult> updateAppointment(
    _i7.AppointmentModel? appointment,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateAppointment, [appointment]),
            returnValue: _i4.Future<_i3.ReturnResult>.value(
              _FakeReturnResult_1(
                this,
                Invocation.method(#updateAppointment, [appointment]),
              ),
            ),
          )
          as _i4.Future<_i3.ReturnResult>);

  @override
  _i4.Future<_i3.ReturnResult> deleteAppointment(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAppointment, [id]),
            returnValue: _i4.Future<_i3.ReturnResult>.value(
              _FakeReturnResult_1(
                this,
                Invocation.method(#deleteAppointment, [id]),
              ),
            ),
          )
          as _i4.Future<_i3.ReturnResult>);

  @override
  _i4.Future<_i3.ReturnResult> updateAppointmentStatus(
    String? id,
    bool? isCompleted,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateAppointmentStatus, [id, isCompleted]),
            returnValue: _i4.Future<_i3.ReturnResult>.value(
              _FakeReturnResult_1(
                this,
                Invocation.method(#updateAppointmentStatus, [id, isCompleted]),
              ),
            ),
          )
          as _i4.Future<_i3.ReturnResult>);
}

/// A class which mocks [AlarmScheduler].
///
/// See the documentation for Mockito's code generation for more information.
class MockAlarmScheduler extends _i1.Mock implements _i8.AlarmScheduler {
  MockAlarmScheduler() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> scheduleMedicineAlarms({
    required String? medicineId,
    required String? medicineName,
    required String? dosage,
    required List<String>? scheduledTimes,
    required DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#scheduleMedicineAlarms, [], {
              #medicineId: medicineId,
              #medicineName: medicineName,
              #dosage: dosage,
              #scheduledTimes: scheduledTimes,
              #startDate: startDate,
              #endDate: endDate,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> scheduleAppointmentAlarm({
    required String? appointmentId,
    required String? title,
    required DateTime? appointmentDate,
    String? location,
    int? reminderMinutesBefore = 30,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#scheduleAppointmentAlarm, [], {
              #appointmentId: appointmentId,
              #title: title,
              #appointmentDate: appointmentDate,
              #location: location,
              #reminderMinutesBefore: reminderMinutesBefore,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> cancelMedicineAlarms(String? medicineId) =>
      (super.noSuchMethod(
            Invocation.method(#cancelMedicineAlarms, [medicineId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> cancelAppointmentAlarm(String? appointmentId) =>
      (super.noSuchMethod(
            Invocation.method(#cancelAppointmentAlarm, [appointmentId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
