// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC32h_HrA5UWvsANzkO_v6yx0SMPt5qG-M',
    appId: '1:1084179893922:web:d15f6c8953099ee56751fb',
    messagingSenderId: '1084179893922',
    projectId: 'gestanea-eb002',
    authDomain: 'gestanea-eb002.firebaseapp.com',
    storageBucket: 'gestanea-eb002.firebasestorage.app',
    measurementId: 'G-LX8W8F8KLS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA9yJI2geK_S4oZQXJ0eTGniIavfs1FTU',
    appId: '1:1084179893922:android:d5c4cf188d97e6656751fb',
    messagingSenderId: '1084179893922',
    projectId: 'gestanea-eb002',
    storageBucket: 'gestanea-eb002.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNYSmdhOI1Tm87fZTLec5l341_-XFgurU',
    appId: '1:1084179893922:ios:346fe48625a163296751fb',
    messagingSenderId: '1084179893922',
    projectId: 'gestanea-eb002',
    storageBucket: 'gestanea-eb002.firebasestorage.app',
    iosBundleId: 'com.example.first',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNYSmdhOI1Tm87fZTLec5l341_-XFgurU',
    appId: '1:1084179893922:ios:346fe48625a163296751fb',
    messagingSenderId: '1084179893922',
    projectId: 'gestanea-eb002',
    storageBucket: 'gestanea-eb002.firebasestorage.app',
    iosBundleId: 'com.example.first',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC32h_HrA5UWvsANzkO_v6yx0SMPt5qG-M',
    appId: '1:1084179893922:web:0378802fd52199486751fb',
    messagingSenderId: '1084179893922',
    projectId: 'gestanea-eb002',
    authDomain: 'gestanea-eb002.firebaseapp.com',
    storageBucket: 'gestanea-eb002.firebasestorage.app',
    measurementId: 'G-64NK5867C4',
  );
}
